FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019

WORKDIR   c:/IP2C.Console
COPY . .


ENV CONSUL_URL=http://consul:8500

ENTRYPOINT IP2CTest.Console.exe -consul %CONSUL_URL%