FROM microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1709

WORKDIR c:/selfhost
COPY . .


ENV CONSUL_URL=http://172.18.240.2:8500
ENV NETWORK=172.18.240.0/20

EXPOSE 80
ENTRYPOINT IP2C.WebAPI.SelfHost.exe -network %NETWORK% -consul %CONSUL_URL%